export type Comp = { id: string; name: string; code: string; type: "earning" | "deduction"; calc: "fixed" | "percent_basic" | "percent_gross"; defaultValue: string; isTaxable: boolean; isProrated: boolean; isStatutory: boolean; sortOrder: number; isActive: boolean };
export type Line = { code: string; name: string; amount: number; full?: number };
export type Pay = { earnings: Line[]; deductions: Line[]; employer: Line[]; gross: number; totalDeductions: number; net: number; employerCost: number };
export type Salary = { id: string; effectiveFrom: string; ctcMonthly: string; components: { componentId: string; code: string; value: number }[]; pfOptIn: boolean; esiOptIn: boolean; ptApplicable: boolean; tdsMonthly: string; paymentMode: string; note: string | null; createdAt: string };
export type Run = { id: string; month: string; branchId: string | null; branchName: string | null; status: string; employeeCount: number; totalGross: string; totalDeductions: string; totalNet: string; totalEmployerCost: string; processedAt: string | null; approvedAt: string | null; paidAt: string | null; note: string | null };
export type Item = { id: string; employeeId: string; employeeName: string; employeeCode: string; designationName: string | null; departmentName: string | null; branchName: string | null; daysInMonth: number; payableDays: string; lopDays: string; attendance: Record<string, number>; earnings: Line[]; deductions: Line[]; employer: Line[]; gross: string; totalDeductions: string; net: string; employerCost: string; status: string; remarks: string | null; bankSnapshot: Record<string, string | null> | null };
export const RSTATUS: Record<string, string> = { draft: "Draft", processing: "Processing", pending_approval: "Pending approval", approved: "Approved", paid: "Paid", cancelled: "Cancelled" };
export const rtone: Record<string, string> = { draft: "draft", processing: "under_review", pending_approval: "pending", approved: "trial", paid: "approved", cancelled: "cancelled" };
export const monthLabel = (m: string) => new Date(`${m}-01T00:00:00Z`).toLocaleDateString("en-IN", { month: "long", year: "numeric", timeZone: "UTC" });
