import { useState } from "react";
import { Plus, Zap } from "lucide-react";
import { useGet, useAction } from "@/lib/queries";
import { PageHeader, Loading, Empty, Field } from "@/components/ui/page";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Modal } from "@/components/ui/modal";
import { fmtDate } from "@/lib/utils";

type Rule = { id: string; name: string; trigger: string; conditions: { field: string; op: string; value: string | number }[]; actions: { type: string; to: string; template?: string; url?: string }[]; isActive: boolean; runCount: number; lastRunAt: string | null };
const OPS: Record<string, string> = { eq: "=", neq: "≠", gt: ">", gte: "≥", lt: "<", lte: "≤", contains: "contains" };
const ACTIONS: Record<string, string> = { notify: "In-app notification", email: "Email", sms: "SMS", whatsapp: "WhatsApp", create_ticket: "Create help desk ticket", webhook: "Call webhook" };
const TO: Record<string, string> = { employee: "the employee", manager: "their manager", hr: "HR", admins: "company admins" };
const EXAMPLES = [
  { name: "Late 3+ times → notify HR", trigger: "attendance.late", conditions: [{ field: "lateCountThisMonth", op: "gte", value: 3 }], actions: [{ type: "notify", to: "hr", template: "{{employeeName}} late {{lateCountThisMonth}} times this month\nPlease review attendance." }] },
  { name: "Subscription expiring → WhatsApp admins", trigger: "subscription.expiring", conditions: [{ field: "daysLeft", op: "lte", value: 7 }], actions: [{ type: "whatsapp", to: "admins", template: "HRMS subscription expires in {{daysLeft}} days" }] },
  { name: "New joiner → IT ticket for laptop", trigger: "employee.joined", conditions: [], actions: [{ type: "create_ticket", to: "hr", template: "Onboarding setup for {{employeeName}}\nLaptop, email and access for {{employeeCode}} ({{departmentId}})." }] },
  { name: "Expense above ₹10,000 → notify admins", trigger: "expense.submitted", conditions: [{ field: "amount", op: "gt", value: 10000 }], actions: [{ type: "notify", to: "admins", template: "High-value expense ₹{{amount}} by {{employeeName}}" }] },
];
export default function Automation() {
  const { data, isLoading } = useGet<Rule[]>(["rules"], "/automation"); const trig = useGet<Record<string, { label: string; fields: string[] }>>(["triggers"], "/automation/triggers");
  const act = useAction([["rules"], ["rule-logs"]]);
  const [m, setM] = useState<any>(null); const [logsFor, setLogsFor] = useState<Rule | null>(null);
  const logs = useGet<any[]>(["rule-logs", logsFor?.id], `/automation/${logsFor?.id}/logs`, !!logsFor);
  const fields = m ? trig.data?.data?.[m.trigger]?.fields ?? [] : [];
  return (
    <>
      <PageHeader title="Automation" sub="IF something happens THEN do something — no code." actions={<Button onClick={() => setM({ name: "", trigger: "attendance.late", conditions: [], actions: [{ type: "notify", to: "hr", template: "" }], isActive: true })}><Plus size={16} /> New rule</Button>} />
      {isLoading ? <Loading /> : !data?.data?.length ? <div className="space-y-3"><Empty text="No rules yet. Start from an example:" /><div className="grid gap-2 md:grid-cols-2">{EXAMPLES.map((ex) => <button key={ex.name} onClick={() => setM({ ...ex, isActive: true })} className="card p-3 text-left hover:border-brand text-sm"><Zap size={14} className="inline mr-1 text-brand" />{ex.name}</button>)}</div></div> : <div className="space-y-2">{data.data.map((r) => (
        <div key={r.id} className="card px-4 py-3 grid gap-2 md:grid-cols-[1fr_auto]"><div>
          <div className="flex items-center gap-2"><span className="font-semibold">{r.name}</span><Badge status={r.isActive ? "active" : "inactive"} />{r.runCount > 0 && <span className="text-xs text-muted">ran {r.runCount}× · last {fmtDate(r.lastRunAt)}</span>}</div>
          <div className="text-sm mt-1"><span className="font-semibold text-brand">IF</span> {trig.data?.data?.[r.trigger]?.label ?? r.trigger}{r.conditions.map((c, i) => <span key={i} className="text-muted"> and {c.field} {OPS[c.op]} {c.value}</span>)} <span className="font-semibold text-brand">THEN</span> {r.actions.map((a) => `${ACTIONS[a.type]} → ${TO[a.to] ?? a.to}`).join(", ")}</div>
        </div><div className="flex gap-1 justify-end"><Button size="sm" variant="ghost" onClick={() => setLogsFor(r)}>Log</Button><Button size="sm" variant="ghost" onClick={() => act.mutate({ url: `/automation/${r.id}/test` })}>Test</Button><Button size="sm" variant="ghost" onClick={() => setM({ ...r })}>Edit</Button><Button size="sm" variant="ghost" onClick={() => act.mutate({ method: "put", url: `/automation/${r.id}`, body: { isActive: !r.isActive } })}>{r.isActive ? "Pause" : "Resume"}</Button><Button size="sm" variant="ghost" className="text-danger" onClick={() => confirm("Delete rule?") && act.mutate({ method: "delete", url: `/automation/${r.id}` })}>Delete</Button></div></div>))}</div>}
      <Modal open={!!m} onClose={() => setM(null)} title={m?.id ? "Edit rule" : "New rule"} wide>{m && <div className="space-y-4">
        <Field label="Rule name"><input className="field" value={m.name} onChange={(e) => setM({ ...m, name: e.target.value })} /></Field>
        <div className="card p-3 space-y-3"><div className="text-sm font-bold text-brand">IF</div><Field label="Trigger"><select className="field" value={m.trigger} onChange={(e) => setM({ ...m, trigger: e.target.value, conditions: [] })}>{Object.entries(trig.data?.data ?? {}).map(([k, t]) => <option key={k} value={k}>{t.label}</option>)}</select></Field>
          {m.conditions.map((c: any, i: number) => <div key={i} className="grid grid-cols-[1fr_100px_1fr_auto] gap-2 items-center"><select className="field" value={c.field} onChange={(e) => { const cs = [...m.conditions]; cs[i] = { ...c, field: e.target.value }; setM({ ...m, conditions: cs }); }}>{fields.map((f) => <option key={f}>{f}</option>)}</select><select className="field" value={c.op} onChange={(e) => { const cs = [...m.conditions]; cs[i] = { ...c, op: e.target.value }; setM({ ...m, conditions: cs }); }}>{Object.entries(OPS).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select><input className="field" value={c.value} onChange={(e) => { const cs = [...m.conditions]; cs[i] = { ...c, value: isNaN(Number(e.target.value)) || e.target.value === "" ? e.target.value : Number(e.target.value) }; setM({ ...m, conditions: cs }); }} /><Button size="sm" variant="ghost" onClick={() => setM({ ...m, conditions: m.conditions.filter((_: any, j: number) => j !== i) })}>✕</Button></div>)}
          <Button size="sm" variant="secondary" disabled={!fields.length} onClick={() => setM({ ...m, conditions: [...m.conditions, { field: fields[0], op: "gte", value: 1 }] })}>+ condition</Button></div>
        <div className="card p-3 space-y-3"><div className="text-sm font-bold text-brand">THEN</div>
          {m.actions.map((a: any, i: number) => <div key={i} className="space-y-2 border-b border-line/60 pb-3 last:border-0"><div className="grid grid-cols-[1fr_1fr_auto] gap-2"><select className="field" value={a.type} onChange={(e) => { const as = [...m.actions]; as[i] = { ...a, type: e.target.value }; setM({ ...m, actions: as }); }}>{Object.entries(ACTIONS).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select>{a.type !== "webhook" ? <select className="field" value={a.to} onChange={(e) => { const as = [...m.actions]; as[i] = { ...a, to: e.target.value }; setM({ ...m, actions: as }); }}>{Object.entries(TO).map(([k, v]) => <option key={k} value={k}>to {v}</option>)}</select> : <input className="field" placeholder="https://…" value={a.url ?? ""} onChange={(e) => { const as = [...m.actions]; as[i] = { ...a, url: e.target.value }; setM({ ...m, actions: as }); }} />}<Button size="sm" variant="ghost" disabled={m.actions.length === 1} onClick={() => setM({ ...m, actions: m.actions.filter((_: any, j: number) => j !== i) })}>✕</Button></div>{a.type !== "webhook" && <textarea className="field" rows={2} placeholder={`First line = title, rest = body. Variables: {{employeeName}} {{employeeCode}} ${fields.map((f) => `{{${f}}}`).join(" ")}`} value={a.template ?? ""} onChange={(e) => { const as = [...m.actions]; as[i] = { ...a, template: e.target.value }; setM({ ...m, actions: as }); }} />}</div>)}
          <Button size="sm" variant="secondary" onClick={() => setM({ ...m, actions: [...m.actions, { type: "notify", to: "hr", template: "" }] })}>+ action</Button></div>
        <div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setM(null)}>Cancel</Button><Button loading={act.isPending} disabled={!m.name} onClick={() => { const { id, runCount, lastRunAt, createdAt, updatedAt, companyId, ...body } = m; act.mutate({ method: id ? "put" : "post", url: id ? `/automation/${id}` : "/automation", body }, { onSuccess: () => setM(null) }); }}>Save rule</Button></div>
      </div>}</Modal>
      <Modal open={!!logsFor} onClose={() => setLogsFor(null)} title={`Log · ${logsFor?.name}`} wide>{logs.isLoading ? <Loading /> : !logs.data?.data?.length ? <Empty text="Not triggered yet. Use Test to fire a sample event." /> : <div className="card divide-y divide-line max-h-[60vh] overflow-y-auto">{logs.data.data.map((l: any) => <div key={l.id} className="px-3 py-2 text-sm flex gap-3"><Badge status={l.result === "ran" ? "approved" : "inactive"}>{l.result}</Badge><span className="flex-1">{l.message}{l.payload?.employeeName && <span className="text-muted"> · {l.payload.employeeName}</span>}</span><span className="text-xs text-muted whitespace-nowrap">{new Date(l.createdAt).toLocaleString("en-IN")}</span></div>)}</div>}</Modal>
    </>
  );
}
