import { useState } from "react";
import { Plus } from "lucide-react";
import { useGet, useAction } from "@/lib/queries";
import { useAuth } from "@/store/auth";
import { PageHeader, Loading, Empty, Field } from "@/components/ui/page";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Modal } from "@/components/ui/modal";
import { cn, fmtDate } from "@/lib/utils";

type Goal = { id: string; employeeId: string; title: string; description: string | null; type: string; targetValue: string | null; currentValue: string | null; unit: string | null; progress: number; weight: number; dueDate: string | null; status: string };
type Cycle = { id: string; name: string; periodStart: string; periodEnd: string; status: string; ratingScale: number; reviewCount: number; completed: number };
type Review = { id: string; employeeId: string; employeeName: string; employeeCode: string; designationName: string | null; cycleName: string; ratingScale: number; cycleStatus: string; selfRating: number | null; selfComments: string | null; managerRating: number | null; managerComments: string | null; hrRating: number | null; hrComments: string | null; finalRating: string | null; status: string };
const rtone: Record<string, string> = { self_pending: "draft", manager_pending: "pending", hr_pending: "under_review", completed: "approved" };
const rlabel: Record<string, string> = { self_pending: "Self review", manager_pending: "Manager review", hr_pending: "HR review", completed: "Completed" };

export function GoalsPanel({ employeeId, canEdit }: { employeeId?: string; canEdit: boolean }) {
  const { data, isLoading } = useGet<Goal[]>(["goals", employeeId], `/performance/goals${employeeId ? `?employeeId=${employeeId}` : ""}`);
  const act = useAction([["goals", employeeId]]);
  const [m, setM] = useState<any>(null);
  if (isLoading) return <Loading />;
  const goals = data?.data ?? [];
  return (
    <div className="space-y-3">
      {canEdit && <div className="flex justify-end"><Button size="sm" onClick={() => setM({ title: "", description: "", type: "goal", targetValue: "", currentValue: "", unit: "", weight: 1, dueDate: "" })}><Plus size={14} /> Goal</Button></div>}
      {!goals.length ? <Empty text="No goals set." /> : goals.map((g) => <div key={g.id} className="card p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><span className="font-semibold">{g.title}</span> <Badge status={g.status === "completed" ? "approved" : g.status === "cancelled" ? "inactive" : "trial"} className="ml-1">{g.type.toUpperCase()} · {g.status}</Badge></div><div className="text-sm text-muted">{g.dueDate && `due ${fmtDate(g.dueDate)} · `}weight {g.weight}{canEdit && <Button size="sm" variant="ghost" className="ml-2" onClick={() => setM({ ...g, targetValue: g.targetValue ?? "", currentValue: g.currentValue ?? "", unit: g.unit ?? "", dueDate: g.dueDate ?? "", description: g.description ?? "" })}>Update</Button>}</div></div>{g.description && <p className="text-sm text-muted mt-1">{g.description}</p>}<div className="mt-2 flex items-center gap-3"><div className="flex-1 h-2 rounded bg-surface-2"><div className={cn("h-full rounded", g.progress >= 100 ? "bg-good" : "bg-brand")} style={{ width: `${g.progress}%` }} /></div><span className="text-sm font-bold tabular-nums w-12 text-right">{g.progress}%</span></div>{g.targetValue && <div className="text-xs text-muted mt-1">{Number(g.currentValue ?? 0).toLocaleString("en-IN")} / {Number(g.targetValue).toLocaleString("en-IN")} {g.unit}</div>}</div>)}
      <Modal open={!!m} onClose={() => setM(null)} title={m?.id ? "Update goal" : "New goal"}>{m && <div className="space-y-3"><Field label="Title"><input className="field" value={m.title} onChange={(e) => setM({ ...m, title: e.target.value })} /></Field><Field label="Description"><textarea className="field" rows={2} value={m.description} onChange={(e) => setM({ ...m, description: e.target.value })} /></Field><div className="grid grid-cols-2 gap-3"><Field label="Type"><select className="field" value={m.type} onChange={(e) => setM({ ...m, type: e.target.value })}><option value="goal">Goal</option><option value="kpi">KPI</option><option value="okr">OKR</option></select></Field><Field label="Weight (1–10)"><input className="field" type="number" min={1} max={10} value={m.weight} onChange={(e) => setM({ ...m, weight: e.target.value })} /></Field><Field label="Target"><input className="field" type="number" value={m.targetValue} onChange={(e) => setM({ ...m, targetValue: e.target.value })} placeholder="e.g. 1000000" /></Field><Field label="Current"><input className="field" type="number" value={m.currentValue} onChange={(e) => setM({ ...m, currentValue: e.target.value })} /></Field><Field label="Unit"><input className="field" value={m.unit} onChange={(e) => setM({ ...m, unit: e.target.value })} placeholder="₹ / leads / %" /></Field><Field label="Due date"><input className="field" type="date" value={m.dueDate} onChange={(e) => setM({ ...m, dueDate: e.target.value })} /></Field>{m.id && <><Field label="Progress % (if no target)"><input className="field" type="number" min={0} max={100} value={m.progress} onChange={(e) => setM({ ...m, progress: e.target.value })} /></Field><Field label="Status"><select className="field" value={m.status} onChange={(e) => setM({ ...m, status: e.target.value })}>{["active", "completed", "cancelled"].map((s) => <option key={s}>{s}</option>)}</select></Field></>}</div><div className="flex justify-end gap-2">{m.id && <Button variant="ghost" className="text-danger mr-auto" onClick={() => confirm("Delete goal?") && act.mutate({ method: "delete", url: `/performance/goals/${m.id}` }, { onSuccess: () => setM(null) })}>Delete</Button>}<Button variant="secondary" onClick={() => setM(null)}>Cancel</Button><Button loading={act.isPending} disabled={!m.title} onClick={() => { const { id, ...b } = m; const body: any = { ...b, employeeId, targetValue: b.targetValue || null, currentValue: b.currentValue || null, unit: b.unit || null, dueDate: b.dueDate || null, description: b.description || null }; if (!id) { delete body.progress; delete body.status; } act.mutate({ method: id ? "put" : "post", url: id ? `/performance/goals/${id}` : "/performance/goals", body }, { onSuccess: () => setM(null) }); }}>Save</Button></div></div>}</Modal>
    </div>
  );
}

function ReviewCard({ r, role, onSubmit }: { r: Review; role: "self" | "manager" | "hr"; onSubmit: (body: any) => void }) {
  const [f, setF] = useState({ rating: 3, comments: "", finalRating: "" });
  const canAct = (role === "self" && r.status === "self_pending") || (role === "manager" && ["self_pending", "manager_pending"].includes(r.status)) || (role === "hr" && r.status === "hr_pending");
  const Rating = ({ v }: { v: number | null }) => v == null ? <span className="text-muted">—</span> : <span className="font-bold">{v}/{r.ratingScale}</span>;
  return (
    <div className="card p-4 space-y-3">
      <div className="flex flex-wrap items-center justify-between gap-2"><div><span className="font-semibold">{r.employeeName}</span> <span className="text-xs text-muted">{r.employeeCode} · {r.designationName ?? ""}</span></div><div className="flex items-center gap-2"><span className="text-xs text-muted">{r.cycleName}</span><Badge status={rtone[r.status]}>{rlabel[r.status]}</Badge>{r.finalRating && <Badge status="approved">Final {Number(r.finalRating)}/{r.ratingScale}</Badge>}</div></div>
      <div className="grid sm:grid-cols-3 gap-3 text-sm">{[["Self", r.selfRating, r.selfComments], ["Manager", r.managerRating, r.managerComments], ["HR", r.hrRating, r.hrComments]].map(([l, v, c]) => <div key={l as string} className="rounded-md bg-surface-2 p-2"><div className="flex justify-between"><span className="text-muted">{l}</span><Rating v={v as number | null} /></div>{c && <p className="text-xs mt-1">{c as string}</p>}</div>)}</div>
      {canAct && r.cycleStatus === "open" && <div className="border-t border-line pt-3 space-y-2"><div className="grid grid-cols-[120px_1fr] gap-3"><Field label={`Rating (1–${r.ratingScale})`}><input className="field" type="number" min={1} max={r.ratingScale} value={f.rating} onChange={(e) => setF({ ...f, rating: Number(e.target.value) })} /></Field><Field label="Comments"><input className="field" value={f.comments} onChange={(e) => setF({ ...f, comments: e.target.value })} /></Field></div>{role === "hr" && <Field label="Override final rating (optional)"><input className="field w-40" type="number" step="0.5" value={f.finalRating} onChange={(e) => setF({ ...f, finalRating: e.target.value })} /></Field>}<div className="flex justify-end"><Button size="sm" disabled={role !== "hr" && !f.comments} onClick={() => onSubmit(role === "hr" ? { rating: f.rating, comments: f.comments, finalRating: f.finalRating ? Number(f.finalRating) : undefined } : { rating: f.rating, comments: f.comments })}>Submit {role} review</Button></div></div>}
    </div>
  );
}

export default function Performance() {
  const { can } = useAuth(); const manage = can("performance.manage");
  const [tab, setTab] = useState<"goals" | "my" | "team" | "cycles">("goals");
  const mine = useGet<Review[]>(["rv-me"], "/performance/reviews/me"); const team = useGet<Review[]>(["rv-team"], "/performance/reviews/team");
  const cycles = useGet<Cycle[]>(["cycles"], "/performance/cycles", tab === "cycles" && manage);
  const [cycleId, setCycleId] = useState<string | null>(null); const cycleReviews = useGet<Review[]>(["rv-cycle", cycleId], `/performance/cycles/${cycleId}/reviews`, !!cycleId);
  const act = useAction([["rv-me"], ["rv-team"], ["cycles"], ["rv-cycle"]]);
  const [m, setM] = useState<any>(null);
  const tabs = [{ k: "goals", l: "My goals", show: true }, { k: "my", l: "My reviews", show: true }, { k: "team", l: "Team reviews", n: team.data?.data?.filter((r) => r.status !== "completed").length, show: true }, { k: "cycles", l: "Review cycles", show: manage }] as const;
  return (
    <>
      <PageHeader title="Performance" sub="Goals, KPIs, OKRs and appraisal cycles." />
      <div className="flex gap-1 border-b border-line mb-5">{tabs.filter((t) => t.show).map((t) => <button key={t.k} onClick={() => setTab(t.k)} className={cn("px-3 py-2 text-sm font-semibold border-b-2 -mb-px", tab === t.k ? "border-brand" : "border-transparent text-muted")}>{t.l}{"n" in t && t.n ? <span className="ml-1.5 rounded-full bg-warn/15 text-warn px-1.5 text-[11px]">{t.n}</span> : null}</button>)}</div>
      {tab === "goals" && <GoalsPanel canEdit />}
      {tab === "my" && (mine.isLoading ? <Loading /> : !mine.data?.data?.length ? <Empty text="No reviews assigned to you." /> : <div className="space-y-3">{mine.data.data.map((r) => <ReviewCard key={r.id} r={r} role="self" onSubmit={(b) => act.mutate({ url: `/performance/reviews/${r.id}/self`, body: b })} />)}</div>)}
      {tab === "team" && (team.isLoading ? <Loading /> : !team.data?.data?.length ? <Empty text="No team reviews in open cycles." /> : <div className="space-y-3">{team.data.data.map((r) => <ReviewCard key={r.id} r={r} role="manager" onSubmit={(b) => act.mutate({ url: `/performance/reviews/${r.id}/manager`, body: b })} />)}</div>)}
      {tab === "cycles" && (cycleId ? <><button onClick={() => setCycleId(null)} className="text-sm text-muted hover:text-ink mb-3">← Cycles</button>{cycleReviews.isLoading ? <Loading /> : <div className="space-y-3">{cycleReviews.data?.data?.map((r) => <ReviewCard key={r.id} r={r} role="hr" onSubmit={(b) => act.mutate({ url: `/performance/reviews/${r.id}/hr`, body: b })} />)}</div>}</> : <>
        <div className="flex justify-end mb-3"><Button onClick={() => setM({ name: "", periodStart: "", periodEnd: "", ratingScale: 5, includeAll: true })}><Plus size={16} /> New cycle</Button></div>
        {cycles.isLoading ? <Loading /> : !cycles.data?.data?.length ? <Empty text="No review cycles yet." /> : <div className="card"><table className="w-full"><thead><tr><th className="th">Cycle</th><th className="th">Period</th><th className="th">Progress</th><th className="th">Status</th><th className="th"></th></tr></thead><tbody>{cycles.data.data.map((c) => <tr key={c.id} className="hover:bg-surface-2/60"><td className="td font-semibold cursor-pointer" onClick={() => setCycleId(c.id)}>{c.name}</td><td className="td text-muted">{fmtDate(c.periodStart)} – {fmtDate(c.periodEnd)}</td><td className="td tabular-nums">{c.completed}/{c.reviewCount}</td><td className="td"><Badge status={c.status === "open" ? "active" : c.status === "closed" ? "inactive" : "draft"}>{c.status}</Badge></td><td className="td text-right"><Button size="sm" variant="ghost" onClick={() => setCycleId(c.id)}>Reviews</Button>{c.status !== "closed" && <Button size="sm" variant="ghost" onClick={() => act.mutate({ url: `/performance/cycles/${c.id}/status`, body: { status: c.status === "open" ? "closed" : "open" } })}>{c.status === "open" ? "Close" : "Open"}</Button>}</td></tr>)}</tbody></table></div>}
        <Modal open={!!m} onClose={() => setM(null)} title="New review cycle">{m && <div className="space-y-3"><Field label="Name"><input className="field" value={m.name} onChange={(e) => setM({ ...m, name: e.target.value })} placeholder="FY 2026-27 H1 appraisal" /></Field><div className="grid grid-cols-3 gap-3"><Field label="Period start"><input className="field" type="date" value={m.periodStart} onChange={(e) => setM({ ...m, periodStart: e.target.value })} /></Field><Field label="Period end"><input className="field" type="date" value={m.periodEnd} onChange={(e) => setM({ ...m, periodEnd: e.target.value })} /></Field><Field label="Rating scale"><select className="field" value={m.ratingScale} onChange={(e) => setM({ ...m, ratingScale: Number(e.target.value) })}>{[5, 10].map((n) => <option key={n} value={n}>1–{n}</option>)}</select></Field></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={m.includeAll} onChange={(e) => setM({ ...m, includeAll: e.target.checked })} />Create a review for every active employee (self → manager → HR)</label><div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setM(null)}>Cancel</Button><Button loading={act.isPending} disabled={!m.name || !m.periodStart || !m.periodEnd} onClick={() => act.mutate({ url: "/performance/cycles", body: m }, { onSuccess: () => setM(null) })}>Create</Button></div></div>}</Modal>
      </>)}
    </>
  );
}
