import { useState } from "react";
import { Plus, Star } from "lucide-react";
import { useGet, useAction } from "@/lib/queries";
import { useAuth } from "@/store/auth";
import { PageHeader, Loading, Empty, Field, Stat } from "@/components/ui/page";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Modal } from "@/components/ui/modal";
import { cn, fmtDate, inr } from "@/lib/utils";
import type { Branch, Dept, Desig } from "../employees/types";

type Job = { id: string; title: string; description: string | null; branchId: string | null; departmentId: string | null; designationId: string | null; departmentName: string | null; designationName: string | null; branchName: string | null; experienceMin: number; experienceMax: number | null; salaryMin: string | null; salaryMax: string | null; location: string | null; skills: string[]; openings: number; employmentType: string; status: string; candidateCount: number; joinedCount: number; createdAt: string };
type Cand = { id: string; name: string; email: string | null; mobile: string | null; resumeUrl: string | null; skills: string[]; experienceYears: string | null; education: string | null; currentCompany: string | null; currentCtc: string | null; expectedCtc: string | null; noticeDays: number | null; source: string | null; stage: string; rating: number | null; notes: string | null; rejectionReason: string | null; offerLetter: string | null; offerSentAt: string | null; employeeId: string | null; updatedAt: string };
type Iv = { id: string; round: number; type: string; scheduledAt: string; durationMin: number; interviewerName: string | null; meetingLink: string | null; location: string | null; status: string; feedback: string | null; rating: number | null; recommendation: string | null };
const STAGES = ["applied", "screening", "interview", "selected", "offer_sent", "joined", "rejected"];
const stone: Record<string, string> = { applied: "draft", screening: "trial", interview: "under_review", selected: "pending", offer_sent: "pending", joined: "approved", rejected: "rejected" };
const jtone: Record<string, string> = { draft: "draft", open: "active", on_hold: "pending", closed: "inactive" };

export default function Recruitment() {
  const { can } = useAuth(); const manage = can("recruitment.manage");
  const [jobId, setJobId] = useState<string | null>(null);
  if (jobId) return <JobDetail id={jobId} back={() => setJobId(null)} />;
  return <Jobs open={setJobId} manage={manage} />;
}

function Jobs({ open, manage }: { open: (id: string) => void; manage: boolean }) {
  const { data, isLoading } = useGet<Job[]>(["jobs"], "/recruitment/jobs"); const stats = useGet<{ openJobs: number; pipeline: { stage: string; n: number }[] }>(["rec-stats"], "/recruitment/stats");
  const branches = useGet<Branch[]>(["branches"], "/branches"); const depts = useGet<Dept[]>(["departments"], "/departments"); const desigs = useGet<Desig[]>(["designations"], "/designations");
  const act = useAction([["jobs"], ["rec-stats"]]);
  const [m, setM] = useState<any>(null); const [tpl, setTpl] = useState(false);
  const p = (s: string) => stats.data?.data?.pipeline.find((x) => x.stage === s)?.n ?? 0;
  return (
    <>
      <PageHeader title="Recruitment" sub="Jobs, candidates, interviews and offers." actions={manage && <><Button variant="secondary" onClick={() => setTpl(true)}>Offer templates</Button><Button onClick={() => setM({ title: "", description: "", branchId: "", departmentId: "", designationId: "", experienceMin: 0, experienceMax: "", salaryMin: "", salaryMax: "", location: "", skills: "", openings: 1, employmentType: "full_time", status: "open" })}><Plus size={16} /> Post job</Button></>} />
      <div className="grid gap-3 grid-cols-2 lg:grid-cols-5 mb-5"><Stat label="Open jobs" value={stats.data?.data?.openJobs ?? 0} /><Stat label="Applied" value={p("applied") + p("screening")} /><Stat label="In interview" value={p("interview")} /><Stat label="Offered" value={p("selected") + p("offer_sent")} tone="warn" /><Stat label="Joined" value={p("joined")} tone="good" /></div>
      {isLoading ? <Loading /> : !data?.data?.length ? <Empty text="No jobs yet. Post your first opening." /> : <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.data.map((j) => <button key={j.id} onClick={() => open(j.id)} className="card p-4 text-left hover:border-brand transition-colors"><div className="flex justify-between items-start gap-2"><h3 className="font-bold">{j.title}</h3><Badge status={jtone[j.status]}>{j.status.replace("_", " ")}</Badge></div><p className="text-xs text-muted mt-0.5">{[j.departmentName, j.branchName ?? j.location].filter(Boolean).join(" · ")} · {j.openings} opening{j.openings > 1 ? "s" : ""}</p><p className="text-sm mt-2">{j.experienceMin}{j.experienceMax ? `–${j.experienceMax}` : "+"} yrs{j.salaryMin && ` · ${inr(j.salaryMin)}${j.salaryMax ? `–${inr(j.salaryMax)}` : ""}`}</p><div className="mt-2 flex flex-wrap gap-1">{j.skills.slice(0, 5).map((s) => <span key={s} className="rounded bg-surface-2 px-1.5 py-0.5 text-[11px]">{s}</span>)}</div><div className="mt-3 text-sm"><b>{j.candidateCount}</b> candidates · <b className="text-good">{j.joinedCount}</b> joined</div></button>)}</div>}
      <Modal open={!!m} onClose={() => setM(null)} title={m?.id ? "Edit job" : "Post a job"} wide>{m && <div className="space-y-4"><div className="grid sm:grid-cols-2 gap-3">
        <Field label="Job title" className="sm:col-span-2"><input className="field" value={m.title} onChange={(e) => setM({ ...m, title: e.target.value })} /></Field>
        <Field label="Department"><select className="field" value={m.departmentId ?? ""} onChange={(e) => setM({ ...m, departmentId: e.target.value })}><option value="">—</option>{depts.data?.data?.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select></Field>
        <Field label="Designation"><select className="field" value={m.designationId ?? ""} onChange={(e) => setM({ ...m, designationId: e.target.value })}><option value="">—</option>{desigs.data?.data?.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select></Field>
        <Field label="Branch"><select className="field" value={m.branchId ?? ""} onChange={(e) => setM({ ...m, branchId: e.target.value })}><option value="">—</option>{branches.data?.data?.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select></Field>
        <Field label="Location"><input className="field" value={m.location ?? ""} onChange={(e) => setM({ ...m, location: e.target.value })} /></Field>
        <Field label="Experience min (yrs)"><input className="field" type="number" value={m.experienceMin} onChange={(e) => setM({ ...m, experienceMin: e.target.value })} /></Field><Field label="Experience max"><input className="field" type="number" value={m.experienceMax ?? ""} onChange={(e) => setM({ ...m, experienceMax: e.target.value })} /></Field>
        <Field label="Salary min (₹/yr)"><input className="field" type="number" value={m.salaryMin ?? ""} onChange={(e) => setM({ ...m, salaryMin: e.target.value })} /></Field><Field label="Salary max"><input className="field" type="number" value={m.salaryMax ?? ""} onChange={(e) => setM({ ...m, salaryMax: e.target.value })} /></Field>
        <Field label="Skills (comma separated)" className="sm:col-span-2"><input className="field" value={Array.isArray(m.skills) ? m.skills.join(", ") : m.skills} onChange={(e) => setM({ ...m, skills: e.target.value })} /></Field>
        <Field label="Openings"><input className="field" type="number" min={1} value={m.openings} onChange={(e) => setM({ ...m, openings: e.target.value })} /></Field><Field label="Status"><select className="field" value={m.status} onChange={(e) => setM({ ...m, status: e.target.value })}>{["draft", "open", "on_hold", "closed"].map((s) => <option key={s} value={s}>{s.replace("_", " ")}</option>)}</select></Field>
        <Field label="Description" className="sm:col-span-2"><textarea className="field" rows={4} value={m.description ?? ""} onChange={(e) => setM({ ...m, description: e.target.value })} /></Field></div>
        <div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setM(null)}>Cancel</Button><Button loading={act.isPending} disabled={!m.title} onClick={() => { const { id, ...b } = m; act.mutate({ method: id ? "put" : "post", url: id ? `/recruitment/jobs/${id}` : "/recruitment/jobs", body: { ...b, skills: typeof b.skills === "string" ? b.skills.split(",").map((s: string) => s.trim()).filter(Boolean) : b.skills, branchId: b.branchId || null, departmentId: b.departmentId || null, designationId: b.designationId || null, experienceMax: b.experienceMax || null, salaryMin: b.salaryMin || null, salaryMax: b.salaryMax || null } }, { onSuccess: () => setM(null) }); }}>Save job</Button></div></div>}</Modal>
      <Modal open={tpl} onClose={() => setTpl(false)} title="Offer letter templates" wide><OfferTemplates /></Modal>
    </>
  );
}

function OfferTemplates() {
  const { data } = useGet<{ templates: { id: string; name: string; body: string; isDefault: boolean }[]; variables: string[]; sample: string }>(["offer-tpl"], "/recruitment/offer-templates");
  const act = useAction([["offer-tpl"]]);
  const [m, setM] = useState<{ id?: string; name: string; body: string; isDefault: boolean } | null>(null);
  if (m) return <div className="space-y-3"><Field label="Template name"><input className="field" value={m.name} onChange={(e) => setM({ ...m, name: e.target.value })} /></Field><Field label={`Body — variables: ${data?.data?.variables.map((v) => `{{${v}}}`).join(" ")}`}><textarea className="field font-mono text-xs" rows={14} value={m.body} onChange={(e) => setM({ ...m, body: e.target.value })} /></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={m.isDefault} onChange={(e) => setM({ ...m, isDefault: e.target.checked })} />Default template</label><div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setM(null)}>Back</Button><Button loading={act.isPending} disabled={!m.name || m.body.length < 10} onClick={() => { const { id, ...b } = m; act.mutate({ method: id ? "put" : "post", url: id ? `/recruitment/offer-templates/${id}` : "/recruitment/offer-templates", body: b }, { onSuccess: () => setM(null) }); }}>Save</Button></div></div>;
  return <div className="space-y-3"><div className="flex justify-end"><Button size="sm" onClick={() => setM({ name: "Standard offer", body: data?.data?.sample ?? "", isDefault: !data?.data?.templates.length })}><Plus size={14} /> Template</Button></div>{!data?.data?.templates.length ? <Empty text="No templates — the built-in sample is used until you add one." /> : data.data.templates.map((t) => <div key={t.id} className="card px-4 py-3 flex items-center justify-between"><span className="font-semibold">{t.name} {t.isDefault && <Badge status="active" className="ml-2">default</Badge>}</span><Button size="sm" variant="ghost" onClick={() => setM({ ...t })}>Edit</Button></div>)}</div>;
}

function JobDetail({ id, back }: { id: string; back: () => void }) {
  const { can } = useAuth(); const manage = can("recruitment.manage");
  const { data, isLoading } = useGet<Job & { candidates: Cand[]; byStage: { stage: string; n: number }[] }>(["job", id], `/recruitment/jobs/${id}`);
  const act = useAction<any, any>([["job", id], ["jobs"], ["rec-stats"], ["cand"]]);
  const [add, setAdd] = useState<any>(null); const [candId, setCandId] = useState<string | null>(null);
  if (isLoading || !data?.data) return <Loading />;
  const j = data.data;
  return (
    <>
      <button onClick={back} className="text-sm text-muted hover:text-ink">← Jobs</button>
      <PageHeader title={j.title} sub={`${[j.departmentName, j.designationName, j.branchName ?? j.location].filter(Boolean).join(" · ")} · ${j.openings} opening${j.openings > 1 ? "s" : ""} · ${j.candidates.length} candidates`} actions={manage && <Button onClick={() => setAdd({ name: "", email: "", mobile: "", resumeUrl: "", skills: "", experienceYears: "", education: "", currentCompany: "", currentCtc: "", expectedCtc: "", noticeDays: "", source: "portal", notes: "" })}><Plus size={16} /> Add candidate</Button>} />
      <div className="overflow-x-auto pb-2"><div className="grid grid-flow-col auto-cols-[240px] gap-3 min-w-max">{STAGES.map((s) => <div key={s} className="rounded-lg bg-surface-2/60 p-2"><div className="flex items-center justify-between px-1 mb-2"><span className="text-[12px] font-bold capitalize">{s.replace("_", " ")}</span><span className="text-[11px] text-muted">{j.byStage.find((x) => x.stage === s)?.n ?? 0}</span></div><div className="space-y-2">{j.candidates.filter((c) => c.stage === s).map((c) => <button key={c.id} onClick={() => setCandId(c.id)} className="card w-full p-3 text-left hover:border-brand"><div className="font-semibold text-sm">{c.name}</div><div className="text-xs text-muted">{c.experienceYears ? `${Number(c.experienceYears)} yrs` : ""}{c.currentCompany ? ` · ${c.currentCompany}` : ""}</div>{c.rating && <div className="flex gap-0.5 mt-1">{Array.from({ length: 5 }, (_, i) => <Star key={i} size={11} className={i < c.rating! ? "fill-warn text-warn" : "text-line"} />)}</div>}</button>)}</div></div>)}</div></div>
      <Modal open={!!add} onClose={() => setAdd(null)} title="Add candidate" wide>{add && <div className="space-y-4"><div className="grid sm:grid-cols-3 gap-3">{[["name", "Full name"], ["email", "Email"], ["mobile", "Mobile"], ["resumeUrl", "Resume link"], ["experienceYears", "Experience (yrs)"], ["education", "Education"], ["currentCompany", "Current company"], ["currentCtc", "Current CTC (₹/yr)"], ["expectedCtc", "Expected CTC"], ["noticeDays", "Notice (days)"]].map(([k, l]) => <Field key={k} label={l}><input className="field" value={add[k]} onChange={(e) => setAdd({ ...add, [k]: e.target.value })} /></Field>)}<Field label="Source"><select className="field" value={add.source} onChange={(e) => setAdd({ ...add, source: e.target.value })}>{["portal", "referral", "linkedin", "walk-in", "agency", "other"].map((s) => <option key={s}>{s}</option>)}</select></Field><Field label="Skills (comma separated)" className="sm:col-span-2"><input className="field" value={add.skills} onChange={(e) => setAdd({ ...add, skills: e.target.value })} /></Field><Field label="Notes" className="sm:col-span-3"><textarea className="field" rows={2} value={add.notes} onChange={(e) => setAdd({ ...add, notes: e.target.value })} /></Field></div><div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setAdd(null)}>Cancel</Button><Button loading={act.isPending} disabled={add.name.length < 2} onClick={() => { const b: any = { ...add, skills: add.skills.split(",").map((s: string) => s.trim()).filter(Boolean) }; for (const k of Object.keys(b)) if (b[k] === "") b[k] = null; act.mutate({ url: `/recruitment/jobs/${id}/candidates`, body: b }, { onSuccess: () => setAdd(null) }); }}>Add</Button></div></div>}</Modal>
      <Modal open={!!candId} onClose={() => setCandId(null)} title="Candidate" wide>{candId && <CandidateView id={candId} job={j} close={() => setCandId(null)} manage={manage} />}</Modal>
    </>
  );
}

function CandidateView({ id, job, close, manage }: { id: string; job: Job; close: () => void; manage: boolean }) {
  const { data, isLoading } = useGet<Cand & { interviews: Iv[] }>(["cand", id], `/recruitment/candidates/${id}`);
  const emps = useGet<{ id: string; name: string }[]>(["managers"], "/employees/managers"); const branches = useGet<Branch[]>(["branches"], "/branches"); const desigs = useGet<Desig[]>(["designations"], "/designations"); const depts = useGet<Dept[]>(["departments"], "/departments");
  const act = useAction([["cand", id], ["job", job.id], ["jobs"], ["rec-stats"], ["employees"], ["cal"]]);
  const [iv, setIv] = useState<any>(null); const [fb, setFb] = useState<any>(null); const [offer, setOffer] = useState<any>(null); const [conv, setConv] = useState<any>(null);
  if (isLoading || !data?.data) return <Loading />;
  const c = data.data;
  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-bold">{c.name}</h3><Badge status={stone[c.stage]}>{c.stage.replace("_", " ")}</Badge>{manage && c.stage !== "joined" && <select className="field h-8 w-40 ml-auto" value={c.stage} onChange={(e) => { const stage = e.target.value; if (stage === "joined") return setConv({ branchId: "", joiningDate: new Date().toISOString().slice(0, 10), designationId: job.designationId ?? "", departmentId: job.departmentId ?? "" }); const rejectionReason = stage === "rejected" ? prompt("Rejection reason") ?? "" : undefined; act.mutate({ url: `/recruitment/candidates/${c.id}/stage`, body: { stage, rejectionReason } }); }}>{STAGES.map((s) => <option key={s} value={s}>{s.replace("_", " ")}</option>)}</select>}</div>
      <div className="grid sm:grid-cols-3 gap-x-4 gap-y-1 text-sm">{[["Email", c.email], ["Mobile", c.mobile], ["Experience", c.experienceYears ? `${Number(c.experienceYears)} yrs` : null], ["Education", c.education], ["Current company", c.currentCompany], ["Current CTC", c.currentCtc ? inr(c.currentCtc) : null], ["Expected CTC", c.expectedCtc ? inr(c.expectedCtc) : null], ["Notice", c.noticeDays ? `${c.noticeDays} days` : null], ["Source", c.source]].map(([k, v]) => <div key={k as string}><span className="text-muted">{k}: </span>{v || "—"}</div>)}{c.resumeUrl && <a href={c.resumeUrl} target="_blank" rel="noreferrer" className="text-brand font-semibold">View resume</a>}</div>
      {c.skills.length > 0 && <div className="flex flex-wrap gap-1">{c.skills.map((s) => <span key={s} className="rounded bg-surface-2 px-1.5 py-0.5 text-[11px]">{s}</span>)}</div>}
      {c.notes && <p className="text-sm text-muted">{c.notes}</p>}{c.rejectionReason && <p className="text-sm text-danger">Rejected: {c.rejectionReason}</p>}
      {manage && <div className="flex items-center gap-2 text-sm"><span className="text-muted">Rating</span>{Array.from({ length: 5 }, (_, i) => <button key={i} onClick={() => act.mutate({ method: "put", url: `/recruitment/candidates/${c.id}`, body: { rating: i + 1 } })}><Star size={16} className={i < (c.rating ?? 0) ? "fill-warn text-warn" : "text-line"} /></button>)}</div>}
      <div><div className="flex items-center justify-between mb-2"><h4 className="font-bold text-sm">Interviews</h4>{manage && !["joined", "rejected"].includes(c.stage) && <Button size="sm" variant="secondary" onClick={() => setIv({ round: c.interviews.length + 1, type: "technical", scheduledAt: "", durationMin: 45, interviewerId: "", meetingLink: "", location: "" })}>Schedule</Button>}</div>
        {!c.interviews.length ? <p className="text-sm text-muted">None scheduled.</p> : <div className="space-y-2">{c.interviews.map((i) => <div key={i.id} className="card px-3 py-2 text-sm flex flex-wrap items-center gap-2"><span className="font-semibold">Round {i.round} · {i.type}</span><span className="text-muted">{new Date(i.scheduledAt).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })} · {i.interviewerName ?? "no interviewer"}{i.meetingLink && <> · <a className="text-brand" href={i.meetingLink} target="_blank" rel="noreferrer">link</a></>}</span><Badge status={i.status === "completed" ? "approved" : i.status === "scheduled" ? "pending" : "inactive"}>{i.status}</Badge>{i.recommendation && <Badge status={i.recommendation === "hire" ? "approved" : i.recommendation === "no_hire" ? "rejected" : "pending"}>{i.recommendation.replace("_", " ")}</Badge>}{i.feedback && <span className="w-full text-xs text-muted">{i.feedback}{i.rating ? ` · ${i.rating}/5` : ""}</span>}{i.status === "scheduled" && <Button size="sm" variant="ghost" className="ml-auto" onClick={() => setFb({ id: i.id, status: "completed", feedback: "", rating: 3, recommendation: "hold" })}>Add feedback</Button>}</div>)}</div>}</div>
      {c.offerLetter && <details className="card p-3"><summary className="text-sm font-bold cursor-pointer">Offer letter (generated {fmtDate(c.offerSentAt)})</summary><pre className="mt-2 whitespace-pre-wrap text-xs font-sans">{c.offerLetter}</pre><Button size="sm" variant="secondary" className="mt-2" onClick={() => navigator.clipboard.writeText(c.offerLetter!)}>Copy text</Button></details>}
      {manage && ["selected", "offer_sent"].includes(c.stage) && <div className="flex gap-2"><Button size="sm" onClick={() => setOffer({ designation: job.designationName ?? job.title, joiningDate: "", salary: c.expectedCtc ?? job.salaryMax ?? "", location: job.location ?? "", offerValidTill: "", department: job.departmentName ?? "" })}>{c.offerLetter ? "Regenerate offer" : "Generate offer letter"}</Button>{c.stage === "offer_sent" && <Button size="sm" variant="secondary" onClick={() => setConv({ branchId: job.branchId ?? "", joiningDate: new Date().toISOString().slice(0, 10), designationId: job.designationId ?? "", departmentId: job.departmentId ?? "" })}>Convert to employee</Button>}</div>}
      {c.employeeId && <p className="text-sm text-good">Joined — employee record created.</p>}
      <Modal open={!!iv} onClose={() => setIv(null)} title="Schedule interview">{iv && <div className="space-y-3"><div className="grid grid-cols-2 gap-3"><Field label="Round"><input className="field" type="number" value={iv.round} onChange={(e) => setIv({ ...iv, round: e.target.value })} /></Field><Field label="Type"><select className="field" value={iv.type} onChange={(e) => setIv({ ...iv, type: e.target.value })}>{["telephonic", "technical", "hr", "final"].map((t) => <option key={t}>{t}</option>)}</select></Field><Field label="Date & time"><input className="field" type="datetime-local" value={iv.scheduledAt} onChange={(e) => setIv({ ...iv, scheduledAt: e.target.value })} /></Field><Field label="Duration (min)"><input className="field" type="number" value={iv.durationMin} onChange={(e) => setIv({ ...iv, durationMin: e.target.value })} /></Field></div><Field label="Interviewer"><select className="field" value={iv.interviewerId} onChange={(e) => setIv({ ...iv, interviewerId: e.target.value })}><option value="">—</option>{emps.data?.data?.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Meeting link / location"><input className="field" value={iv.meetingLink} onChange={(e) => setIv({ ...iv, meetingLink: e.target.value })} placeholder="https://meet.google.com/… or Conference room" /></Field><div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setIv(null)}>Cancel</Button><Button loading={act.isPending} disabled={!iv.scheduledAt} onClick={() => act.mutate({ url: `/recruitment/candidates/${c.id}/interviews`, body: { ...iv, scheduledAt: new Date(iv.scheduledAt).toISOString(), interviewerId: iv.interviewerId || null, meetingLink: iv.meetingLink || null } }, { onSuccess: () => setIv(null) })}>Schedule</Button></div></div>}</Modal>
      <Modal open={!!fb} onClose={() => setFb(null)} title="Interview feedback">{fb && <div className="space-y-3"><div className="grid grid-cols-3 gap-3"><Field label="Outcome"><select className="field" value={fb.status} onChange={(e) => setFb({ ...fb, status: e.target.value })}><option value="completed">Completed</option><option value="no_show">No show</option><option value="cancelled">Cancelled</option></select></Field><Field label="Rating (1–5)"><input className="field" type="number" min={1} max={5} value={fb.rating} onChange={(e) => setFb({ ...fb, rating: e.target.value })} /></Field><Field label="Recommendation"><select className="field" value={fb.recommendation} onChange={(e) => setFb({ ...fb, recommendation: e.target.value })}><option value="hire">Hire</option><option value="hold">Hold</option><option value="no_hire">No hire</option></select></Field></div><Field label="Feedback"><textarea className="field" rows={4} value={fb.feedback} onChange={(e) => setFb({ ...fb, feedback: e.target.value })} /></Field><div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setFb(null)}>Cancel</Button><Button loading={act.isPending} onClick={() => act.mutate({ url: `/recruitment/interviews/${fb.id}/feedback`, body: { ...fb, id: undefined, rating: Number(fb.rating) } }, { onSuccess: () => setFb(null) })}>Save</Button></div></div>}</Modal>
      <Modal open={!!offer} onClose={() => setOffer(null)} title="Generate offer letter">{offer && <div className="space-y-3"><div className="grid grid-cols-2 gap-3">{[["designation", "Designation"], ["department", "Department"], ["joiningDate", "Joining date"], ["salary", "Annual CTC (₹)"], ["location", "Location"], ["offerValidTill", "Offer valid till"]].map(([k, l]) => <Field key={k} label={l}><input className="field" type={k.includes("Date") || k === "offerValidTill" ? "date" : "text"} value={offer[k]} onChange={(e) => setOffer({ ...offer, [k]: e.target.value })} /></Field>)}</div><div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setOffer(null)}>Cancel</Button><Button loading={act.isPending} disabled={!offer.designation || !offer.joiningDate || !offer.salary} onClick={() => act.mutate({ url: `/recruitment/candidates/${c.id}/offer`, body: { ...offer, salary: Number(offer.salary) } }, { onSuccess: () => setOffer(null) })}>Generate</Button></div></div>}</Modal>
      <Modal open={!!conv} onClose={() => setConv(null)} title={`Convert ${c.name} to employee`}>{conv && <div className="space-y-3"><Field label="Branch"><select className="field" value={conv.branchId} onChange={(e) => setConv({ ...conv, branchId: e.target.value })}><option value="">Select…</option>{branches.data?.data?.filter((b) => b.status === "active").map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="Designation"><select className="field" value={conv.designationId} onChange={(e) => setConv({ ...conv, designationId: e.target.value })}><option value="">—</option>{desigs.data?.data?.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select></Field><Field label="Department"><select className="field" value={conv.departmentId} onChange={(e) => setConv({ ...conv, departmentId: e.target.value })}><option value="">—</option>{depts.data?.data?.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select></Field></div><Field label="Joining date"><input className="field" type="date" value={conv.joiningDate} onChange={(e) => setConv({ ...conv, joiningDate: e.target.value })} /></Field><p className="text-xs text-muted">Creates an employee in probation status with an auto employee code. Counts against your plan's employee limit.</p><div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setConv(null)}>Cancel</Button><Button loading={act.isPending} disabled={!conv.branchId} onClick={() => act.mutate({ url: `/recruitment/candidates/${c.id}/convert`, body: { ...conv, designationId: conv.designationId || null, departmentId: conv.departmentId || null } }, { onSuccess: () => { setConv(null); close(); } })}>Create employee</Button></div></div>}</Modal>
    </div>
  );
}
void cn;
